language: node_js
node_js:
  - 10

services:
  - mysql

before_install:
  - mysql -e 'CREATE SCHEMA tyba ;'

env:
  - TYBA_PORT=3000
  - LOCAL_KEY=f0a56275fcfed1119e3568e3
  - RAPID_API=https://tripadvisor1.p.rapidapi.com
  - RAPID_HOST=tripadvisor1.p.rapidapi.com
  - RAPID_KEY=0b9f8803f2mshb36f115c691c926p19913ajsnc3f81b1d8c14